name: My First GitHub Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions"

      - name: Show Python Version
        run: python --version

      - name: Show Runner OS
        run: uname -a
