name: Java Maven CI with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze Java Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and analyze with SonarQube
        working-directory: java-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.region=us \
            -Dsonar.organization=yuvi2102 \
            -Dsonar.projectKey=Yuvi2102_github-actions-practice
